version: "3"
services:
  jupyter:
    build:
      context: .
      dockerfile: Dockerfile
    deploy:
      resources:
        limits:
          cpus: '1.0'
    ports:
      - 8888:8888
    volumes:
      - ./src:/app